// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendnet.Data;

#nullable disable

namespace backendnet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoriaPelicula", b =>
                {
                    b.Property<int>("CategoriasCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("PeliculasPeliculaId")
                        .HasColumnType("int");

                    b.HasKey("CategoriasCategoriaId", "PeliculasPeliculaId");

                    b.HasIndex("PeliculasPeliculaId");

                    b.ToTable("CategoriaPelicula");
                });

            modelBuilder.Entity("backendnet.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nombre = "Acción",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nombre = "Aventura",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nombre = "Animación",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nombre = "Ciencia Ficción",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 5,
                            Nombre = "Comedia",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 6,
                            Nombre = "Crimen",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 7,
                            Nombre = "Documental",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 8,
                            Nombre = "Drama",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 9,
                            Nombre = "Familiar",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 10,
                            Nombre = "Fantasía",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 11,
                            Nombre = "Historia",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 12,
                            Nombre = "Horror",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 13,
                            Nombre = "Música",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 14,
                            Nombre = "Misterio",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 15,
                            Nombre = "Romance",
                            Protegida = true
                        });
                });

            modelBuilder.Entity("backendnet.Models.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeliculaId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PeliculaId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            Anio = 1994,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg",
                            Sinopsis = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Titulo = "The Shawshank Redemption"
                        },
                        new
                        {
                            PeliculaId = 2,
                            Anio = 1972,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            Sinopsis = "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
                            Titulo = "The Godfather"
                        },
                        new
                        {
                            PeliculaId = 3,
                            Anio = 2008,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Sinopsis = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Titulo = "The Dark Knight"
                        },
                        new
                        {
                            PeliculaId = 4,
                            Anio = 1957,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg",
                            Sinopsis = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            Titulo = "12 Angry Men"
                        },
                        new
                        {
                            PeliculaId = 5,
                            Anio = 1993,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
                            Sinopsis = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution.",
                            Titulo = "Schindler's List"
                        },
                        new
                        {
                            PeliculaId = 6,
                            Anio = 1995,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/6Sj9wDu3YugthXsU0Vry5XFAZGg.jpg",
                            Sinopsis = "In a future world devastated by disease, a convict is sent back in time to gather information, but makes a shocking discovery about the true nature of the scheme.",
                            Titulo = "12 Monkeys"
                        },
                        new
                        {
                            PeliculaId = 7,
                            Anio = 1950,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8f1l2alXHqO1e8WZlJv4m6l4D5l.jpg",
                            Sinopsis = "After a heinous crime transpires in a forest, conflicting accounts arise and multiple perspectives are presented to the court.",
                            Titulo = "Rashōmon"
                        },
                        new
                        {
                            PeliculaId = 8,
                            Anio = 1999,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/4yJyaw7JGzF5g8itkZ5jX3GQ1j3.jpg",
                            Sinopsis = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
                            Titulo = "Fight Club"
                        },
                        new
                        {
                            PeliculaId = 9,
                            Anio = 2019,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/5Eiqj4p0o7j5hHv8Fp8tv0j1H9R.jpg",
                            Sinopsis = "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.",
                            Titulo = "The Lighthouse"
                        },
                        new
                        {
                            PeliculaId = 10,
                            Anio = 1999,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/hEpWvX6Bp79eLxY1kX5ZZJcme5U.jpg",
                            Sinopsis = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Titulo = "The Matrix"
                        },
                        new
                        {
                            PeliculaId = 11,
                            Anio = 1980,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9fgh3Ns1iRzlQNYuJyK0ARQZU7w.jpg",
                            Sinopsis = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
                            Titulo = "The Shining"
                        },
                        new
                        {
                            PeliculaId = 12,
                            Anio = 1990,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7y3eYvTsGjxPYDtSnumCLIMDkrV.jpg",
                            Sinopsis = "Mourning his dead child, a haunted Vietnam War veteran attempts to uncover his past while suffering from a severe case of dissociation. To do so, he must decipher reality and life from his own dreams, delusions, and perceptions of death.",
                            Titulo = "Jacob's Ladder"
                        },
                        new
                        {
                            PeliculaId = 13,
                            Anio = 1982,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                            Sinopsis = "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
                            Titulo = "The Thing"
                        },
                        new
                        {
                            PeliculaId = 14,
                            Anio = 2000,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/fQMSaP88cf1nz4qwuNEEFtazuDM.jpg",
                            Sinopsis = "An amnesiac man is determined to track down the man who raped and murdered his wife.",
                            Titulo = "Memento"
                        },
                        new
                        {
                            PeliculaId = 15,
                            Anio = 1991,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7s7f7c0mQwv2F5qex3Oe7K5VFj.jpg",
                            Sinopsis = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            Titulo = "The Silence of the Lambs"
                        },
                        new
                        {
                            PeliculaId = 16,
                            Anio = 2003,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8YyJWVrjZzY3fZ1RlZJbC8GKbBD.jpg",
                            Sinopsis = "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
                            Titulo = "Oldboy"
                        },
                        new
                        {
                            PeliculaId = 17,
                            Anio = 2006,
                            Poster = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7SGGUiTE6oc2fh9MjIk5M00dsQd.jpg",
                            Sinopsis = "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
                            Titulo = "The Prestige"
                        });
                });

            modelBuilder.Entity("CategoriaPelicula", b =>
                {
                    b.HasOne("backendnet.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendnet.Models.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasPeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
